require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe LeaveConfigsController do

  # This should return the minimal set of attributes required to create a valid
  # LeaveConfig. As you add validations to LeaveConfig, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "emptype" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # LeaveConfigsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all leave_configs as @leave_configs" do
      leave_config = LeaveConfig.create! valid_attributes
      get :index, {}, valid_session
      assigns(:leave_configs).should eq([leave_config])
    end
  end

  describe "GET show" do
    it "assigns the requested leave_config as @leave_config" do
      leave_config = LeaveConfig.create! valid_attributes
      get :show, {:id => leave_config.to_param}, valid_session
      assigns(:leave_config).should eq(leave_config)
    end
  end

  describe "GET new" do
    it "assigns a new leave_config as @leave_config" do
      get :new, {}, valid_session
      assigns(:leave_config).should be_a_new(LeaveConfig)
    end
  end

  describe "GET edit" do
    it "assigns the requested leave_config as @leave_config" do
      leave_config = LeaveConfig.create! valid_attributes
      get :edit, {:id => leave_config.to_param}, valid_session
      assigns(:leave_config).should eq(leave_config)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new LeaveConfig" do
        expect {
          post :create, {:leave_config => valid_attributes}, valid_session
        }.to change(LeaveConfig, :count).by(1)
      end

      it "assigns a newly created leave_config as @leave_config" do
        post :create, {:leave_config => valid_attributes}, valid_session
        assigns(:leave_config).should be_a(LeaveConfig)
        assigns(:leave_config).should be_persisted
      end

      it "redirects to the created leave_config" do
        post :create, {:leave_config => valid_attributes}, valid_session
        response.should redirect_to(LeaveConfig.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved leave_config as @leave_config" do
        # Trigger the behavior that occurs when invalid params are submitted
        LeaveConfig.any_instance.stub(:save).and_return(false)
        post :create, {:leave_config => { "emptype" => "invalid value" }}, valid_session
        assigns(:leave_config).should be_a_new(LeaveConfig)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        LeaveConfig.any_instance.stub(:save).and_return(false)
        post :create, {:leave_config => { "emptype" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested leave_config" do
        leave_config = LeaveConfig.create! valid_attributes
        # Assuming there are no other leave_configs in the database, this
        # specifies that the LeaveConfig created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        LeaveConfig.any_instance.should_receive(:update_attributes).with({ "emptype" => "MyString" })
        put :update, {:id => leave_config.to_param, :leave_config => { "emptype" => "MyString" }}, valid_session
      end

      it "assigns the requested leave_config as @leave_config" do
        leave_config = LeaveConfig.create! valid_attributes
        put :update, {:id => leave_config.to_param, :leave_config => valid_attributes}, valid_session
        assigns(:leave_config).should eq(leave_config)
      end

      it "redirects to the leave_config" do
        leave_config = LeaveConfig.create! valid_attributes
        put :update, {:id => leave_config.to_param, :leave_config => valid_attributes}, valid_session
        response.should redirect_to(leave_config)
      end
    end

    describe "with invalid params" do
      it "assigns the leave_config as @leave_config" do
        leave_config = LeaveConfig.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        LeaveConfig.any_instance.stub(:save).and_return(false)
        put :update, {:id => leave_config.to_param, :leave_config => { "emptype" => "invalid value" }}, valid_session
        assigns(:leave_config).should eq(leave_config)
      end

      it "re-renders the 'edit' template" do
        leave_config = LeaveConfig.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        LeaveConfig.any_instance.stub(:save).and_return(false)
        put :update, {:id => leave_config.to_param, :leave_config => { "emptype" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested leave_config" do
      leave_config = LeaveConfig.create! valid_attributes
      expect {
        delete :destroy, {:id => leave_config.to_param}, valid_session
      }.to change(LeaveConfig, :count).by(-1)
    end

    it "redirects to the leave_configs list" do
      leave_config = LeaveConfig.create! valid_attributes
      delete :destroy, {:id => leave_config.to_param}, valid_session
      response.should redirect_to(leave_configs_url)
    end
  end

end
